channelId: 1
key: "wUhLDGWwKTvEiOSU"
mongo:
  url: "mongodb://pdladmin:sgftpdl66PDC.2020%24%24@150.95.115.104:27017/sgfpdldb"
baokim:
  transferMoneyUrl: "http://210.245.80.186:9095/Sandbox/FirmBanking"
  collectionUrl: "http://210.245.80.186:8085/Sandbox/Collection/V2"
  partnercode: "VAYSV"
  privatekey: "key/test/private.pem"
  publickey: "key/test/public.pem"
  publickeyBaokim: "key/test/baokim/public.pem"
  accType:
    account: 1
    card: 0
  operation:
    transferMoney: 9002
    checkTransaction: 9003
  disbursement:
    operation:
      verifyCustomer: 9001
      transferMoney: 9002
      checkTransaction: 9003
  virtualaccount:
    operation:
      create: 9001
      update: 9002
      search: 9003
      transaction: 9004
    settings:
      createtype: 2
