channelId: 1
key: "wUhLDGWwKTvEiOSU"

baokim:
  bankNo: "970403"
  url: "http://210.245.80.186:8085/Sandbox/Collection/V2"
  urlPayment: "https://sandbox-api.baokim.vn/payment"
  privatekey: "keyRSA/private.pem"
  publickey: "keyRSA/public.pem"
  accType:
    account: 1
    card: 0
  operation:
    transferMoney: 9002
    checkTransaction: 9003
