channelId: 1
key: "wUhLDGWwKTvEiOSU"
mongo:
  url: "mongodb://pdladmin:sgftpdl66PDC.2020%24%24@150.95.115.104:27017/sgfpdldb"
baokim:
  bankNo: "970403"
  urlPayment: "https://sandbox-api.baokim.vn/payment"
  privatekey: "key/private.pem"
  publickey: "key/public.pem"
  accType:
    account: 1
    card: 0
  operation:
    transferMoney: 9002
    checkTransaction: 9003
  disbursement:
    url: ""
    urlapptest: "http://210.245.80.186:9095/Sandbox/FirmBanking"
    # urlapptest: 'http://13.250.110.81:9095/Sandbox/FirmBanking'
    data: "config/disbursement-data.json"
    privatekey: "key/vaysv/private.pem"
    publickey: "key/vaysv/public.pem"
  virtualaccount:
    url: "http://210.245.80.186:8085/Sandbox/Collection/V2"
    privatekey: "key/private.pem"
    publickey: "key/public.pem"
    partnercode: "VAYSV"
    operation:
      create: 9001
      update: 9002
      search: 9003
      transaction: 9004
    settings:
      createtype: 2
